### ISSUE TITLE
Hello, when will you upload the code? thank you

### ISSUE THREAD

**Issue by paizhongxing** [kgarg8/kpgen-lowres-data-aug#1]

**Comment by kgarg8** [comment]
Hi paizhongxing,

Thanks for your interest in our work. We are currently occupied with the EMNLP deadline.

We will try to upload the code asap (probably after 23rd June).

**Comment by nanxi8888** [comment]
Hello, I am very interested in your paper, Can you upload the code？thank you

**Comment by kgarg8** [comment]
Hi nanxi8888,

Thanks for your interest. We will upload the code on the coming weekend. Thanks for your patience.

**Comment by kgarg8** [comment]
Done finally. Thanks all for your patience.
